---
- name: Install NodeJS
  ansible.builtin.apt:
    name: nodejs
    state: present
  become: yes

- name: Install NPM
  ansible.builtin.apt:
    name: npm
    state: present
  become: yes

- name: Install npm modules required by our app
  ansible.builtin.npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ node_npm_modules }}"
